name: dawakhaana
description: DUHacks 4.0 Instant Medicine Delivery Application project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0' # Using the higher SDK constraint for compatibility

dependencies:
  flutter:
    sdk: flutter

  # razorpay integration
  razorpay_flutter: ^1.3.7

  # location access enable
  location: ^8.0.0

  # UI and Icons
  cupertino_icons: ^1.0.8 # Using the latest version

  # Firebase Dependencies
  firebase_core: ^3.12.0 # Using the latest stable version
  firebase_auth: ^5.5.0 # Using the latest stable version
  cloud_firestore: ^5.6.4 # Added from the first version

  # Geolocation
  geolocator: ^13.0.2 # Using the latest version

  # Google Sign-In
  google_sign_in: ^6.2.2 # Using the latest version

  # Local Storage
  shared_preferences: ^2.5.2 # Using the latest version

  # State Management
  provider: ^6.1.2 # Added from the second version

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0 # Using the latest version for better linting support  flutter_projects: any
